es:
  image: madkom/eventstore-docker:latest
#  Your data need to be placed in /data, or this value need to be changed to your current working dir
  volumes:
   - /data/EventStore/data/db:/data/db
   - /data/EventStore/data/logs:/data/logs
client:
  image: madkom/event-sourcing-php-client:latest
#  Your data need to be placed in /data, or this value need to be changed to your current working dir
  volumes:
    - /data/Client:/var/www
  links:
    - es:eventstore
  labels:
    - "io.rancher.sidekicks:es"
clientlb:
  ports:
    - 80:80
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
    - client:client
  stdin_open: true
#banking:
#  build: Banking
#  ports:
#    - "3003:80"
#  volumes:
#    - ./Banking:/var/www
#  links:
#    - es
